[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "Posts"
identifier = "posts"
weight = 200
url = "/posts"

[[main]]
name = "Portfolio"
identifier = "portfolio"
weight = 300
url = "/portfolio"

[[main]]
name = "Resume"
identifier = "resume"
weight = 300
url = "https://drive.google.com/file/d/1cHjH0utyloZfpiV5WOm1KvgFy-QcOfYt/view?usp=drive_link"
