[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "Posts"
identifier = "posts"
weight = 200
url = "/posts"

[[main]]
name = "Portfolio"
identifier = "portfolio"
weight = 300
url = "/portfolio"

