[[main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[main]]
name = "Posts"
identifier = "posts"
weight = 200
url = "/posts"

[[main]]
name = "Portfolio"
identifier = "portfolio"
weight = 300
url = "/portfolio"

[[main]]
name = "Resume"
identifier = "resume"
weight = 300
url = "https://akhilerm.s3.amazonaws.com/akhilerm.pdf"
