title = "Akhil"
author = "Akhil Mohan"
description = "Engineer | Thinker | Learner"
profilePicture = "images/akhilerm.jpg"
favicon = "favicons/"
disableThemeSwitcher = true
contentRatio = 0.7
gtagId = "G-3QDB62WNH6"


mainSections = []

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/akhilerm"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/akhilerm"

[[socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/akhilerm"

[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:akhilerm@gmail.com"


[[socialIcons]]
icon = "far fa-file"
title = "Resume"
url = "https://drive.google.com/file/d/18iqN-hAFUllOhUFkkZxKeZ2U3568Cwp_/view?usp=drive_link"
